language: ruby
rvm:
 - "2.2.3"
cache:
  - directories:
    - $HOME/.cache/pip
    - vendor/bundle
before_install:
  - sudo apt-get update
  - sudo service postgresql stop
  - sudo apt-get remove -y postgresql*
  - git submodule update --recursive --init

install:
before_script:
  - sudo pip install ansible==1.9.4
  - export inf_dir=./infrastructure
  - echo "127.0.0.1 localhost "`hostname` | sudo tee /etc/hosts
  - cd $inf_dir
  - if [ -e ansible_requirements.txt ]; then ansible-galaxy install -p ./ansible/roles -r ansible_requirements.txt; fi
  - sudo ansible-playbook -i 'default,' -e "store_branch=$TRAVIS_COMMIT owner_user_name=$USER client_user_name=$USER" ansible/genomicsdb-webserver.yml --connection=local
  - source /home/genomicsdb/venv/bin/activate
  - pip install pytest pytest-cov coverage pytest-flask pytest-mock
  - pip install sqlalchemy-utils
  - source $HOME/.bashrc
  - echo "127.0.0.1 localhost "`hostname` | sudo tee /etc/hosts
  - curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles
  - echo "source $HOME/.rvm/scripts/rvm" >> ~/.bash_profile

script:
#  - cd $TRAVIS_BUILD_DIR
  - cd /home/genomicsdb/repos/GenomicsSampleAPIs
  - py.test --cov .
  - rvm reload
  - rvm cleanup all
  - rvm install 2.2.3
  - gem install bundler
  - source $HOME/.rvm/scripts/rvm
  - bundle install
  - rake serverspec:site


sudo: required
dist: trusty
