---
- name: set variable dependencies_path
  set_fact : dependencies_path={{store_dir}}/search_library/dependencies

- name: set variable libcsv_path
  set_fact: libcsv_path={{dependencies_path}}/libcsv-master

- name: Create the libcsv_path 
  file: 
    path  : "{{libcsv_path}}"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"
    state : directory

- name: Get package
  get_url:
    dest: "{{dependencies_path}}/libcsv.zip"
    url : https://github.com/robertpostill/libcsv/archive/master.zip

# force override with unzip -o 
- name: Prepare libcsv package
  shell: >
    cd {{dependencies_path}} &&
    unzip -o libcsv.zip &&
    cd {{libcsv_path}} &&
    autoreconf --install &&
    ./configure &&
    make
