# The MIT License (MIT)
# Copyright (c) 2016 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of 
# this software and associated documentation files (the "Software"), to deal in 
# the Software without restriction, including without limitation the rights to 
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
# the Software, and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

---
- name     : Set variable mpi_path
  set_fact : mpi_path={{default_mpi_path}}
  when     : mpi_path is not defined

- name     : Set variable mpi_runner
  set_fact : mpi_runner={{default_mpi_runner}}
  when     : mpi_runner is not defined

- name     : Set variable env_path
  set_fact : 
    env_path: "{{GenomicsDB_bin_dir}}:{{gcc_prefix}}/bin:{{mpi_path}}/bin:$PATH"
  when     : env_path is not defined

- name     : Set variable env_ld_library_path
  set_fact : 
    env_ld_library_path: "{{gcc_prefix}}/lib:{{gcc_prefix}}/lib64:{{htslib_dir}}:{{mpi_path}}/lib:$LD_LIBRARY_PATH"
  when     : env_ld_library_path is not defined and libcsv_path is not defined

- name     : Set variable env_ld_library_path
  set_fact : 
    env_ld_library_path: "{{gcc_prefix}}/lib:{{gcc_prefix}}/lib64:{{htslib_dir}}:{{libcsv_path}}/.libs:{{mpi_path}}/lib:$LD_LIBRARY_PATH"
  when     : env_ld_library_path is not defined and libcsv_path is defined

- name     : Set variable env_pythonpath
  set_fact : 
    env_pythonpath: "{{store_dir}}:$PYTHONPATH"
  when     : env_pythonpath is not defined

- name       : Setup environment variable PATH for users
  lineinfile :
    dest: "/home/{{item}}/.bashrc"
    line: "export PATH={{env_path}}"
  with_items: "{{users_list}}"

- name       : Setup environment variable LD_LIBRARY_PATH for users
  lineinfile :
    dest: "/home/{{item}}/.bashrc"
    line: "export LD_LIBRARY_PATH={{env_ld_library_path}}"
  with_items: "{{users_list}}"

- name       : Setup environment variable PYTHONPATH for users
  lineinfile :
    dest: "/home/{{item}}/.bashrc"
    line: "export PYTHONPATH={{env_pythonpath}}"
  with_items: "{{users_list}}"

- name     : Set variable ga4gh_virtualenv 
  set_fact : ga4gh_virtualenv={{genomicsdb_dir}}/venv
  when     : ga4gh_virtualenv is not defined

- name : Create and install virtualenv for GA4GH webserver
  pip  : 
    requirements             : "{{store_dir}}/requirements.txt"
    virtualenv               : "{{ga4gh_virtualenv}}"
  become      : yes
  become_user : "{{owner_user_name}}"

- name        : Force install psycopg2 package in virtualenv
  shell       : ". {{ga4gh_virtualenv}}/bin/activate && pip install -U --force psycopg2"
  become      : yes
  become_user : "{{owner_user_name}}"

- name: Run python setup.py to install the modules into the virtualenv
  shell: ". {{ga4gh_virtualenv}}/bin/activate && python setup.py develop"
  args  : 
    chdir : "{{store_dir}}"
  become      : yes
  become_user : "{{owner_user_name}}"

- name     : Set variable mappingdb_adapter
  set_fact : mappingdb_adapter="{{default_mappingdb_adapter}}"
  when     : mappingdb_adapter is not defined

- name     : Set variable mappingdb_uri
  set_fact : mappingdb_uri="{{mappingdb_adapter}}://@:5432/{{mappingdb_name}}"
  when     : mappingdb_uri is not defined

- name     : Update alembic.ini
  template : 
    src   : alembic.ini.j2 
    dest  : "{{store_dir}}/mappingdb/alembic.ini"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name  : Run alembic upgrade to head
  shell : ". {{ga4gh_virtualenv}}/bin/activate && alembic upgrade head"
  args  : 
    chdir : "{{store_dir}}/mappingdb"
  become      : yes
  become_user : "{{owner_user_name}}"

# Priviledges have to be granted on the tables after it is created by alembic.
- name : Grant SELECT-only priviledges to the client on the DB
  postgresql_privs :
    db           : "{{mappingdb_name}}"
    role         : "{{client_user_name}}"
    state        : present
    privs        : SELECT
    objs         : ALL_IN_SCHEMA
  become      : yes
  become_user : postgres
  when        : client_user_name != owner_user_name
