---
- name: set variable dependencies_path
  set_fact : dependencies_path={{store_dir}}/search_library/dependencies

- name: set variable libcsv_path
  set_fact: libcsv_path={{dependencies_path}}/libcsv

- name: Create the libcsv_path 
  file: 
    path  : "{{libcsv_path}}"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"
    state : directory

- name : GIT pull libcsv repo
  git:
    repo           : https://github.com/robertpostill/libcsv.git
    dest           : "{{store_dir}}"
    version        : master
  become         : yes
  become_user    : "{{owner_user_name}}"

- name: Prepare libcsv package
  shell: >
    cd {{libcsv_path}} &&
    ./configure &&
    make

