---
- name     : Set fact templates_dir
  set_fact : templates_dir={{store_dir}}/web/templates
  when     : templates_dir is not defined

- name: Create the templates_dir directory with the right permissions
  file: 
    path  : "{{templates_dir}}"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"
    state : directory

- name     : Setup ga4gh ini template
  template :
    src   : ga4gh.ini.j2 
    dest  : "{{store_dir}}/web/templates/ga4gh.ini.template"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup ga4gh conf template
  template :
    src   : ga4gh.conf.j2 
    dest  : "{{store_dir}}/web/templates/ga4gh.conf.template"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup ga4gh service template
  template :
    src  : "ga4gh.service.{{ansible_os_family}}.j2"
    dest : "{{store_dir}}/web/templates/ga4gh.{{template_system_services_extension}}.template"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup nginx conf file template
  template :
    src  : nginx.conf.j2 
    dest : "{{store_dir}}/web/templates/nginx_ga4gh.conf.template"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup tiledb_loader template
  template :
    src  : tiledb_loader.json.j2
    dest : "{{store_dir}}/utils/example_configs/tiledb_loader.json"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name     : Setup load_to_tile.cfg template
  template :
    src  : load_to_tile.cfg.j2
    dest : "{{store_dir}}/utils/example_configs/load_to_tile.cfg"
    group : "{{group_name}}"
    owner : "{{owner_user_name}}"
    mode  : "{{permissions}}"

- name: fix path on the callset_mapping_file
  replace:
    dest: "{{store_dir}}/test/data/test.callset_mapping"
    regexp: '\/path'
    replace: "{{store_dir}}/test/data"
